# Generated by Django 4.2.7 on 2024-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0120_examticket_drop_code_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_course',
            field=models.BooleanField(default=False, help_text='Should the course be listed as a featured course on the landing page?', verbose_name='Listed on landing page'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_period',
            field=models.CharField(help_text="A human-readable description of the course: Curriculum,Level (e.g. 'Zimsec,Form 4')", max_length=200, null=True, verbose_name='Course label'),
        ),
        migrations.AlterField(
            model_name='flowaccessexceptionentry',
            name='permission',
            field=models.CharField(choices=[('view', 'View the flow'), ('submit_answer', 'Submit answers'), ('end_session', 'End session'), ('change_answer', 'Change already-graded answer'), ('see_correctness', 'See whether an answer is correct'), ('see_answer_before_submission', 'See the correct answer before answering'), ('see_answer_after_submission', 'See the correct answer after answering'), ('cannot_see_flow_result', 'Cannot see flow result'), ('set_roll_over_expiration_mode', "Set the session to 'roll over' expiration mode"), ('see_session_time', 'See session time'), ('lock_down_as_exam_session', 'Lock down as exam session'), ('send_email_about_flow_page', 'Send emails about the flow page to course staff'), ('hide_point_count', 'Hide point count')], max_length=50, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='participationpreapproval',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='+', to='course.participationrole', verbose_name='Roles'),
        ),
    ]
