version: '3'

services:
  app:
    build: .
#    image: relate:latest
    command: /run-relate.sh
    environment:
      DBHOST: db
      DBUSER: myuser
      DBPASS: mypass
    links:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword
